---
- name: Converge
  hosts: all

  vars:
    # controller:
    #   user_email: "user@example.com"
    #   user_password: "mySecurePassword"
    #   fqdn: "controller.mydomain.com"
    #   validate_certs: false
    #   api_key: ""

  tasks:
    - include_role:
        name: ansible-role-nginx-controller-agent
